export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS';

export const LOGOUT = 'LOGOUT';

export const RESET_SIGNUP_SUCCEED = 'RESET_SIGNUP_SUCCEED';
