// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

namespace BilHub.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("backend.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AcceptedTypes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AffiliatedSectionId")
                        .HasColumnType("int");

                    b.Property<string>("AssignmentDescriptionFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CanBeGradedByStudents")
                        .HasColumnType("bit");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsItGraded")
                        .HasColumnType("bit");

                    b.Property<int>("MaxFileSizeInBytes")
                        .HasColumnType("int");

                    b.Property<bool>("VisibilityOfSubmission")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AffiliatedSectionId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcceptedTypes = "pdf,doc,docx",
                            AffiliatedSectionId = 1,
                            AssignmentDescriptionFile = "Odev",
                            CanBeGradedByStudents = true,
                            CourseId = 1,
                            CreatedAt = new DateTime(2021, 4, 26, 14, 28, 37, 159, DateTimeKind.Local).AddTicks(1323),
                            DueDate = new DateTime(2021, 5, 15, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            IsItGraded = true,
                            MaxFileSizeInBytes = 1024,
                            VisibilityOfSubmission = true
                        },
                        new
                        {
                            Id = 2,
                            AcceptedTypes = "pdf,doc,docx",
                            AffiliatedSectionId = 1,
                            AssignmentDescriptionFile = "315 proje",
                            CanBeGradedByStudents = false,
                            CourseId = 2,
                            CreatedAt = new DateTime(2021, 4, 26, 14, 28, 37, 159, DateTimeKind.Local).AddTicks(2442),
                            DueDate = new DateTime(2021, 5, 15, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            IsItGraded = false,
                            MaxFileSizeInBytes = 1024,
                            VisibilityOfSubmission = false
                        });
                });

            modelBuilder.Entity("backend.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CommentedSubmissionId")
                        .HasColumnType("int");

                    b.Property<int>("CommentedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FileAttachmentAvailability")
                        .HasColumnType("bit");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Grade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxGrade")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CommentedSubmissionId");

                    b.HasIndex("CommentedUserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("backend.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseSemester")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LockDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxGroupSize")
                        .HasColumnType("int");

                    b.Property<int>("MinGroupSize")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseInformation = "Object Oriented Software Engineering",
                            CourseSemester = "spring",
                            EndDate = new DateTime(2021, 5, 15, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            LockDate = new DateTime(2021, 4, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            MaxGroupSize = 6,
                            MinGroupSize = 5,
                            Name = "CS 319",
                            StartDate = new DateTime(2021, 2, 15, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CourseInformation = "Programming Languages",
                            CourseSemester = "spring",
                            EndDate = new DateTime(2021, 5, 15, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            LockDate = new DateTime(2021, 4, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            MaxGroupSize = 3,
                            MinGroupSize = 2,
                            Name = "CS 315",
                            StartDate = new DateTime(2021, 2, 15, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CourseInformation = "Data Structures and Algorithms",
                            CourseSemester = "spring",
                            EndDate = new DateTime(2021, 5, 15, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            LockDate = new DateTime(2021, 4, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            MaxGroupSize = 1,
                            MinGroupSize = 1,
                            Name = "CS 202",
                            StartDate = new DateTime(2021, 2, 15, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CourseInformation = "Computer Organization and Architecture",
                            CourseSemester = "spring",
                            EndDate = new DateTime(2021, 5, 15, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            LockDate = new DateTime(2021, 4, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            MaxGroupSize = 3,
                            MinGroupSize = 2,
                            Name = "CS 224",
                            StartDate = new DateTime(2021, 2, 15, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CourseInformation = "History",
                            CourseSemester = "spring",
                            EndDate = new DateTime(2021, 5, 15, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            LockDate = new DateTime(2021, 4, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            MaxGroupSize = 5,
                            MinGroupSize = 4,
                            Name = "Hist 200",
                            StartDate = new DateTime(2021, 2, 15, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CourseInformation = "Calculus",
                            CourseSemester = "spring",
                            EndDate = new DateTime(2021, 5, 15, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            LockDate = new DateTime(2021, 4, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            MaxGroupSize = 1,
                            MinGroupSize = 1,
                            Name = "Math 101",
                            StartDate = new DateTime(2021, 2, 15, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("backend.Models.CourseUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseUsers");

                    b.HasData(
                        new
                        {
                            UserId = 2,
                            CourseId = 1
                        },
                        new
                        {
                            UserId = 16,
                            CourseId = 1
                        },
                        new
                        {
                            UserId = 17,
                            CourseId = 1
                        },
                        new
                        {
                            UserId = 18,
                            CourseId = 2
                        },
                        new
                        {
                            UserId = 15,
                            CourseId = 3
                        },
                        new
                        {
                            UserId = 21,
                            CourseId = 3
                        },
                        new
                        {
                            UserId = 19,
                            CourseId = 4
                        },
                        new
                        {
                            UserId = 22,
                            CourseId = 4
                        },
                        new
                        {
                            UserId = 23,
                            CourseId = 2
                        },
                        new
                        {
                            UserId = 20,
                            CourseId = 6
                        },
                        new
                        {
                            UserId = 15,
                            CourseId = 5
                        });
                });

            modelBuilder.Entity("backend.Models.JoinRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Accepted")
                        .HasColumnType("bit");

                    b.Property<int>("AcceptedNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestedGroupId")
                        .HasColumnType("int");

                    b.Property<int>("RequestingStudentId")
                        .HasColumnType("int");

                    b.Property<bool>("Resolved")
                        .HasColumnType("bit");

                    b.Property<string>("VotedStudents")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RequestedGroupId");

                    b.HasIndex("RequestingStudentId");

                    b.ToTable("JoinRequests");
                });

            modelBuilder.Entity("backend.Models.MergeRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Accepted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReceiverGroupId")
                        .HasColumnType("int");

                    b.Property<bool>("Resolved")
                        .HasColumnType("bit");

                    b.Property<int>("SenderGroupId")
                        .HasColumnType("int");

                    b.Property<string>("VotedStudents")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverGroupId");

                    b.HasIndex("SenderGroupId");

                    b.ToTable("MergeRequests");
                });

            modelBuilder.Entity("backend.Models.PeerGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AffiliatedSectionID")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Grade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxGrade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProjectGroupId")
                        .HasColumnType("int");

                    b.Property<int>("RevieweeId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AffiliatedSectionID");

                    b.HasIndex("ProjectGroupId");

                    b.ToTable("PeerGrades");
                });

            modelBuilder.Entity("backend.Models.PeerGradeAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssignmentDescriptionFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .IsUnique();

                    b.ToTable("PeerGradeAssignments");
                });

            modelBuilder.Entity("backend.Models.ProjectGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Grade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GradedProjectGroupID")
                        .HasColumnType("int");

                    b.Property<int>("GradingUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxGrade")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GradedProjectGroupID");

                    b.HasIndex("GradingUserId");

                    b.ToTable("ProjectGrades");
                });

            modelBuilder.Entity("backend.Models.ProjectGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AffiliatedCourseId")
                        .HasColumnType("int");

                    b.Property<int>("AffiliatedSectionId")
                        .HasColumnType("int");

                    b.Property<bool>("ConfirmationState")
                        .HasColumnType("bit");

                    b.Property<string>("ConfirmedGroupMembers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConfirmedUserNumber")
                        .HasColumnType("int");

                    b.Property<string>("ProjectInformation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AffiliatedCourseId");

                    b.HasIndex("AffiliatedSectionId");

                    b.ToTable("ProjectGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AffiliatedCourseId = 1,
                            AffiliatedSectionId = 1,
                            ConfirmationState = false,
                            ConfirmedGroupMembers = "",
                            ConfirmedUserNumber = 0,
                            ProjectInformation = "BilHub Class Helper"
                        },
                        new
                        {
                            Id = 5,
                            AffiliatedCourseId = 1,
                            AffiliatedSectionId = 1,
                            ConfirmationState = false,
                            ConfirmedGroupMembers = "",
                            ConfirmedUserNumber = 0,
                            ProjectInformation = "Abduls Class Helper"
                        },
                        new
                        {
                            Id = 2,
                            AffiliatedCourseId = 1,
                            AffiliatedSectionId = 2,
                            ConfirmationState = false,
                            ConfirmedGroupMembers = "",
                            ConfirmedUserNumber = 0,
                            ProjectInformation = "Classrom Helper"
                        },
                        new
                        {
                            Id = 3,
                            AffiliatedCourseId = 2,
                            AffiliatedSectionId = 1,
                            ConfirmationState = false,
                            ConfirmedGroupMembers = "",
                            ConfirmedUserNumber = 0,
                            ProjectInformation = "AGA Language"
                        },
                        new
                        {
                            Id = 4,
                            AffiliatedCourseId = 2,
                            AffiliatedSectionId = 2,
                            ConfirmationState = false,
                            ConfirmedGroupMembers = "",
                            ConfirmedUserNumber = 0,
                            ProjectInformation = "Satis Language"
                        });
                });

            modelBuilder.Entity("backend.Models.ProjectGroupUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectGroupId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ProjectGroupId");

                    b.HasIndex("ProjectGroupId");

                    b.ToTable("ProjectGroupUsers");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ProjectGroupId = 1
                        },
                        new
                        {
                            UserId = 3,
                            ProjectGroupId = 1
                        },
                        new
                        {
                            UserId = 4,
                            ProjectGroupId = 1
                        },
                        new
                        {
                            UserId = 5,
                            ProjectGroupId = 1
                        },
                        new
                        {
                            UserId = 6,
                            ProjectGroupId = 1
                        },
                        new
                        {
                            UserId = 7,
                            ProjectGroupId = 1
                        },
                        new
                        {
                            UserId = 11,
                            ProjectGroupId = 2
                        },
                        new
                        {
                            UserId = 12,
                            ProjectGroupId = 2
                        },
                        new
                        {
                            UserId = 13,
                            ProjectGroupId = 2
                        },
                        new
                        {
                            UserId = 24,
                            ProjectGroupId = 2
                        },
                        new
                        {
                            UserId = 25,
                            ProjectGroupId = 5
                        },
                        new
                        {
                            UserId = 1,
                            ProjectGroupId = 3
                        },
                        new
                        {
                            UserId = 3,
                            ProjectGroupId = 3
                        },
                        new
                        {
                            UserId = 4,
                            ProjectGroupId = 3
                        },
                        new
                        {
                            UserId = 5,
                            ProjectGroupId = 4
                        },
                        new
                        {
                            UserId = 6,
                            ProjectGroupId = 4
                        },
                        new
                        {
                            UserId = 7,
                            ProjectGroupId = 4
                        });
                });

            modelBuilder.Entity("backend.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AffiliatedCourseId")
                        .HasColumnType("int");

                    b.Property<int>("SectionNo")
                        .HasColumnType("int");

                    b.Property<bool>("SectionlessState")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AffiliatedCourseId");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AffiliatedCourseId = 1,
                            SectionNo = 1,
                            SectionlessState = false
                        },
                        new
                        {
                            Id = 2,
                            AffiliatedCourseId = 1,
                            SectionNo = 2,
                            SectionlessState = false
                        },
                        new
                        {
                            Id = 3,
                            AffiliatedCourseId = 2,
                            SectionNo = 1,
                            SectionlessState = true
                        },
                        new
                        {
                            Id = 4,
                            AffiliatedCourseId = 2,
                            SectionNo = 2,
                            SectionlessState = true
                        },
                        new
                        {
                            Id = 5,
                            AffiliatedCourseId = 3,
                            SectionNo = 1,
                            SectionlessState = false
                        },
                        new
                        {
                            Id = 6,
                            AffiliatedCourseId = 4,
                            SectionNo = 1,
                            SectionlessState = false
                        },
                        new
                        {
                            Id = 7,
                            AffiliatedCourseId = 4,
                            SectionNo = 2,
                            SectionlessState = false
                        },
                        new
                        {
                            Id = 8,
                            AffiliatedCourseId = 5,
                            SectionNo = 2,
                            SectionlessState = false
                        },
                        new
                        {
                            Id = 9,
                            AffiliatedCourseId = 6,
                            SectionNo = 1,
                            SectionlessState = false
                        });
                });

            modelBuilder.Entity("backend.Models.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AffiliatedAssignmentId")
                        .HasColumnType("int");

                    b.Property<int?>("AffiliatedGroupId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasSubmission")
                        .HasColumnType("bit");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AffiliatedAssignmentId");

                    b.HasIndex("AffiliatedGroupId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("DarkModeStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SecondPasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VerifiedStatus")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DarkModeStatus = false,
                            Email = "cagri@durgut",
                            Name = "Cagri Durgut",
                            PasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            PasswordSalt = new byte[] { 93, 192, 116, 88, 137, 98, 211, 57, 165, 237, 91, 121, 203, 91, 158, 191, 186, 179, 131, 11, 226, 61, 219, 18, 163, 169, 0, 155, 127, 246, 119, 208, 73, 93, 161, 199, 237, 231, 96, 44, 244, 139, 90, 22, 167, 122, 21, 243, 154, 118, 143, 183, 232, 31, 108, 44, 122, 59, 120, 14, 188, 93, 103, 143, 215, 51, 209, 135, 106, 51, 214, 248, 12, 33, 186, 142, 154, 9, 164, 221, 230, 173, 37, 191, 195, 30, 127, 252, 71, 35, 237, 55, 102, 121, 159, 229, 243, 137, 217, 128, 170, 16, 113, 49, 249, 254, 221, 168, 177, 30, 208, 116, 195, 73, 32, 110, 50, 23, 207, 220, 52, 238, 130, 50, 37, 250, 49, 153 },
                            SecondPasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            UserType = 0,
                            VerificationCode = "31",
                            VerifiedStatus = true
                        },
                        new
                        {
                            Id = 2,
                            DarkModeStatus = false,
                            Email = "eray@tuzun",
                            Name = "Eray Tuzun",
                            PasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            PasswordSalt = new byte[] { 93, 192, 116, 88, 137, 98, 211, 57, 165, 237, 91, 121, 203, 91, 158, 191, 186, 179, 131, 11, 226, 61, 219, 18, 163, 169, 0, 155, 127, 246, 119, 208, 73, 93, 161, 199, 237, 231, 96, 44, 244, 139, 90, 22, 167, 122, 21, 243, 154, 118, 143, 183, 232, 31, 108, 44, 122, 59, 120, 14, 188, 93, 103, 143, 215, 51, 209, 135, 106, 51, 214, 248, 12, 33, 186, 142, 154, 9, 164, 221, 230, 173, 37, 191, 195, 30, 127, 252, 71, 35, 237, 55, 102, 121, 159, 229, 243, 137, 217, 128, 170, 16, 113, 49, 249, 254, 221, 168, 177, 30, 208, 116, 195, 73, 32, 110, 50, 23, 207, 220, 52, 238, 130, 50, 37, 250, 49, 153 },
                            SecondPasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            UserType = 0,
                            VerificationCode = "31",
                            VerifiedStatus = true
                        },
                        new
                        {
                            Id = 3,
                            DarkModeStatus = false,
                            Email = "baris@ogun",
                            Name = "Baris Ogun",
                            PasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            PasswordSalt = new byte[] { 93, 192, 116, 88, 137, 98, 211, 57, 165, 237, 91, 121, 203, 91, 158, 191, 186, 179, 131, 11, 226, 61, 219, 18, 163, 169, 0, 155, 127, 246, 119, 208, 73, 93, 161, 199, 237, 231, 96, 44, 244, 139, 90, 22, 167, 122, 21, 243, 154, 118, 143, 183, 232, 31, 108, 44, 122, 59, 120, 14, 188, 93, 103, 143, 215, 51, 209, 135, 106, 51, 214, 248, 12, 33, 186, 142, 154, 9, 164, 221, 230, 173, 37, 191, 195, 30, 127, 252, 71, 35, 237, 55, 102, 121, 159, 229, 243, 137, 217, 128, 170, 16, 113, 49, 249, 254, 221, 168, 177, 30, 208, 116, 195, 73, 32, 110, 50, 23, 207, 220, 52, 238, 130, 50, 37, 250, 49, 153 },
                            SecondPasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            UserType = 0,
                            VerificationCode = "31",
                            VerifiedStatus = true
                        },
                        new
                        {
                            Id = 4,
                            DarkModeStatus = false,
                            Email = "ozgur@demir",
                            Name = "Ozgur Chadoglu",
                            PasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            PasswordSalt = new byte[] { 93, 192, 116, 88, 137, 98, 211, 57, 165, 237, 91, 121, 203, 91, 158, 191, 186, 179, 131, 11, 226, 61, 219, 18, 163, 169, 0, 155, 127, 246, 119, 208, 73, 93, 161, 199, 237, 231, 96, 44, 244, 139, 90, 22, 167, 122, 21, 243, 154, 118, 143, 183, 232, 31, 108, 44, 122, 59, 120, 14, 188, 93, 103, 143, 215, 51, 209, 135, 106, 51, 214, 248, 12, 33, 186, 142, 154, 9, 164, 221, 230, 173, 37, 191, 195, 30, 127, 252, 71, 35, 237, 55, 102, 121, 159, 229, 243, 137, 217, 128, 170, 16, 113, 49, 249, 254, 221, 168, 177, 30, 208, 116, 195, 73, 32, 110, 50, 23, 207, 220, 52, 238, 130, 50, 37, 250, 49, 153 },
                            SecondPasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            UserType = 0,
                            VerificationCode = "31",
                            VerifiedStatus = true
                        },
                        new
                        {
                            Id = 5,
                            DarkModeStatus = false,
                            Email = "yusuf@kawai",
                            Name = "Yusuf Uyar",
                            PasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            PasswordSalt = new byte[] { 93, 192, 116, 88, 137, 98, 211, 57, 165, 237, 91, 121, 203, 91, 158, 191, 186, 179, 131, 11, 226, 61, 219, 18, 163, 169, 0, 155, 127, 246, 119, 208, 73, 93, 161, 199, 237, 231, 96, 44, 244, 139, 90, 22, 167, 122, 21, 243, 154, 118, 143, 183, 232, 31, 108, 44, 122, 59, 120, 14, 188, 93, 103, 143, 215, 51, 209, 135, 106, 51, 214, 248, 12, 33, 186, 142, 154, 9, 164, 221, 230, 173, 37, 191, 195, 30, 127, 252, 71, 35, 237, 55, 102, 121, 159, 229, 243, 137, 217, 128, 170, 16, 113, 49, 249, 254, 221, 168, 177, 30, 208, 116, 195, 73, 32, 110, 50, 23, 207, 220, 52, 238, 130, 50, 37, 250, 49, 153 },
                            SecondPasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            UserType = 0,
                            VerificationCode = "31",
                            VerifiedStatus = true
                        },
                        new
                        {
                            Id = 6,
                            DarkModeStatus = false,
                            Email = "aybala@karakaya",
                            Name = "Aybala karakaya",
                            PasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            PasswordSalt = new byte[] { 93, 192, 116, 88, 137, 98, 211, 57, 165, 237, 91, 121, 203, 91, 158, 191, 186, 179, 131, 11, 226, 61, 219, 18, 163, 169, 0, 155, 127, 246, 119, 208, 73, 93, 161, 199, 237, 231, 96, 44, 244, 139, 90, 22, 167, 122, 21, 243, 154, 118, 143, 183, 232, 31, 108, 44, 122, 59, 120, 14, 188, 93, 103, 143, 215, 51, 209, 135, 106, 51, 214, 248, 12, 33, 186, 142, 154, 9, 164, 221, 230, 173, 37, 191, 195, 30, 127, 252, 71, 35, 237, 55, 102, 121, 159, 229, 243, 137, 217, 128, 170, 16, 113, 49, 249, 254, 221, 168, 177, 30, 208, 116, 195, 73, 32, 110, 50, 23, 207, 220, 52, 238, 130, 50, 37, 250, 49, 153 },
                            SecondPasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            UserType = 0,
                            VerificationCode = "31",
                            VerifiedStatus = true
                        },
                        new
                        {
                            Id = 7,
                            DarkModeStatus = false,
                            Email = "oguzhan@ozcelik",
                            Name = "oguzhan ozcelik",
                            PasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            PasswordSalt = new byte[] { 93, 192, 116, 88, 137, 98, 211, 57, 165, 237, 91, 121, 203, 91, 158, 191, 186, 179, 131, 11, 226, 61, 219, 18, 163, 169, 0, 155, 127, 246, 119, 208, 73, 93, 161, 199, 237, 231, 96, 44, 244, 139, 90, 22, 167, 122, 21, 243, 154, 118, 143, 183, 232, 31, 108, 44, 122, 59, 120, 14, 188, 93, 103, 143, 215, 51, 209, 135, 106, 51, 214, 248, 12, 33, 186, 142, 154, 9, 164, 221, 230, 173, 37, 191, 195, 30, 127, 252, 71, 35, 237, 55, 102, 121, 159, 229, 243, 137, 217, 128, 170, 16, 113, 49, 249, 254, 221, 168, 177, 30, 208, 116, 195, 73, 32, 110, 50, 23, 207, 220, 52, 238, 130, 50, 37, 250, 49, 153 },
                            SecondPasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            UserType = 0,
                            VerificationCode = "31",
                            VerifiedStatus = true
                        },
                        new
                        {
                            Id = 8,
                            DarkModeStatus = false,
                            Email = "berke@ceran",
                            Name = "HOCAM SIMDI BIZ SOYLE BI SISTEM DUSUNDUK DE",
                            PasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            PasswordSalt = new byte[] { 93, 192, 116, 88, 137, 98, 211, 57, 165, 237, 91, 121, 203, 91, 158, 191, 186, 179, 131, 11, 226, 61, 219, 18, 163, 169, 0, 155, 127, 246, 119, 208, 73, 93, 161, 199, 237, 231, 96, 44, 244, 139, 90, 22, 167, 122, 21, 243, 154, 118, 143, 183, 232, 31, 108, 44, 122, 59, 120, 14, 188, 93, 103, 143, 215, 51, 209, 135, 106, 51, 214, 248, 12, 33, 186, 142, 154, 9, 164, 221, 230, 173, 37, 191, 195, 30, 127, 252, 71, 35, 237, 55, 102, 121, 159, 229, 243, 137, 217, 128, 170, 16, 113, 49, 249, 254, 221, 168, 177, 30, 208, 116, 195, 73, 32, 110, 50, 23, 207, 220, 52, 238, 130, 50, 37, 250, 49, 153 },
                            SecondPasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            UserType = 0,
                            VerificationCode = "31",
                            VerifiedStatus = true
                        },
                        new
                        {
                            Id = 9,
                            DarkModeStatus = false,
                            Email = "funda@tan",
                            Name = "Funda Tan",
                            PasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            PasswordSalt = new byte[] { 93, 192, 116, 88, 137, 98, 211, 57, 165, 237, 91, 121, 203, 91, 158, 191, 186, 179, 131, 11, 226, 61, 219, 18, 163, 169, 0, 155, 127, 246, 119, 208, 73, 93, 161, 199, 237, 231, 96, 44, 244, 139, 90, 22, 167, 122, 21, 243, 154, 118, 143, 183, 232, 31, 108, 44, 122, 59, 120, 14, 188, 93, 103, 143, 215, 51, 209, 135, 106, 51, 214, 248, 12, 33, 186, 142, 154, 9, 164, 221, 230, 173, 37, 191, 195, 30, 127, 252, 71, 35, 237, 55, 102, 121, 159, 229, 243, 137, 217, 128, 170, 16, 113, 49, 249, 254, 221, 168, 177, 30, 208, 116, 195, 73, 32, 110, 50, 23, 207, 220, 52, 238, 130, 50, 37, 250, 49, 153 },
                            SecondPasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            UserType = 0,
                            VerificationCode = "31",
                            VerifiedStatus = true
                        },
                        new
                        {
                            Id = 10,
                            DarkModeStatus = false,
                            Email = "hami@mert",
                            Name = "Hami Mert",
                            PasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            PasswordSalt = new byte[] { 93, 192, 116, 88, 137, 98, 211, 57, 165, 237, 91, 121, 203, 91, 158, 191, 186, 179, 131, 11, 226, 61, 219, 18, 163, 169, 0, 155, 127, 246, 119, 208, 73, 93, 161, 199, 237, 231, 96, 44, 244, 139, 90, 22, 167, 122, 21, 243, 154, 118, 143, 183, 232, 31, 108, 44, 122, 59, 120, 14, 188, 93, 103, 143, 215, 51, 209, 135, 106, 51, 214, 248, 12, 33, 186, 142, 154, 9, 164, 221, 230, 173, 37, 191, 195, 30, 127, 252, 71, 35, 237, 55, 102, 121, 159, 229, 243, 137, 217, 128, 170, 16, 113, 49, 249, 254, 221, 168, 177, 30, 208, 116, 195, 73, 32, 110, 50, 23, 207, 220, 52, 238, 130, 50, 37, 250, 49, 153 },
                            SecondPasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            UserType = 0,
                            VerificationCode = "31",
                            VerifiedStatus = true
                        },
                        new
                        {
                            Id = 11,
                            DarkModeStatus = false,
                            Email = "cagri@eren",
                            Name = "Cagri Eren",
                            PasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            PasswordSalt = new byte[] { 93, 192, 116, 88, 137, 98, 211, 57, 165, 237, 91, 121, 203, 91, 158, 191, 186, 179, 131, 11, 226, 61, 219, 18, 163, 169, 0, 155, 127, 246, 119, 208, 73, 93, 161, 199, 237, 231, 96, 44, 244, 139, 90, 22, 167, 122, 21, 243, 154, 118, 143, 183, 232, 31, 108, 44, 122, 59, 120, 14, 188, 93, 103, 143, 215, 51, 209, 135, 106, 51, 214, 248, 12, 33, 186, 142, 154, 9, 164, 221, 230, 173, 37, 191, 195, 30, 127, 252, 71, 35, 237, 55, 102, 121, 159, 229, 243, 137, 217, 128, 170, 16, 113, 49, 249, 254, 221, 168, 177, 30, 208, 116, 195, 73, 32, 110, 50, 23, 207, 220, 52, 238, 130, 50, 37, 250, 49, 153 },
                            SecondPasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            UserType = 0,
                            VerificationCode = "31",
                            VerifiedStatus = true
                        },
                        new
                        {
                            Id = 12,
                            DarkModeStatus = false,
                            Email = "guven@gerger",
                            Name = "Guven Gerger",
                            PasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            PasswordSalt = new byte[] { 93, 192, 116, 88, 137, 98, 211, 57, 165, 237, 91, 121, 203, 91, 158, 191, 186, 179, 131, 11, 226, 61, 219, 18, 163, 169, 0, 155, 127, 246, 119, 208, 73, 93, 161, 199, 237, 231, 96, 44, 244, 139, 90, 22, 167, 122, 21, 243, 154, 118, 143, 183, 232, 31, 108, 44, 122, 59, 120, 14, 188, 93, 103, 143, 215, 51, 209, 135, 106, 51, 214, 248, 12, 33, 186, 142, 154, 9, 164, 221, 230, 173, 37, 191, 195, 30, 127, 252, 71, 35, 237, 55, 102, 121, 159, 229, 243, 137, 217, 128, 170, 16, 113, 49, 249, 254, 221, 168, 177, 30, 208, 116, 195, 73, 32, 110, 50, 23, 207, 220, 52, 238, 130, 50, 37, 250, 49, 153 },
                            SecondPasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            UserType = 0,
                            VerificationCode = "31",
                            VerifiedStatus = true
                        },
                        new
                        {
                            Id = 13,
                            DarkModeStatus = false,
                            Email = "onur@korkmaz",
                            Name = "Onur Korkmaz",
                            PasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            PasswordSalt = new byte[] { 93, 192, 116, 88, 137, 98, 211, 57, 165, 237, 91, 121, 203, 91, 158, 191, 186, 179, 131, 11, 226, 61, 219, 18, 163, 169, 0, 155, 127, 246, 119, 208, 73, 93, 161, 199, 237, 231, 96, 44, 244, 139, 90, 22, 167, 122, 21, 243, 154, 118, 143, 183, 232, 31, 108, 44, 122, 59, 120, 14, 188, 93, 103, 143, 215, 51, 209, 135, 106, 51, 214, 248, 12, 33, 186, 142, 154, 9, 164, 221, 230, 173, 37, 191, 195, 30, 127, 252, 71, 35, 237, 55, 102, 121, 159, 229, 243, 137, 217, 128, 170, 16, 113, 49, 249, 254, 221, 168, 177, 30, 208, 116, 195, 73, 32, 110, 50, 23, 207, 220, 52, 238, 130, 50, 37, 250, 49, 153 },
                            SecondPasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            UserType = 0,
                            VerificationCode = "31",
                            VerifiedStatus = true
                        },
                        new
                        {
                            Id = 14,
                            DarkModeStatus = false,
                            Email = "fuat@schwarzenegger",
                            Name = "Fuat Schwarzengger",
                            PasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            PasswordSalt = new byte[] { 93, 192, 116, 88, 137, 98, 211, 57, 165, 237, 91, 121, 203, 91, 158, 191, 186, 179, 131, 11, 226, 61, 219, 18, 163, 169, 0, 155, 127, 246, 119, 208, 73, 93, 161, 199, 237, 231, 96, 44, 244, 139, 90, 22, 167, 122, 21, 243, 154, 118, 143, 183, 232, 31, 108, 44, 122, 59, 120, 14, 188, 93, 103, 143, 215, 51, 209, 135, 106, 51, 214, 248, 12, 33, 186, 142, 154, 9, 164, 221, 230, 173, 37, 191, 195, 30, 127, 252, 71, 35, 237, 55, 102, 121, 159, 229, 243, 137, 217, 128, 170, 16, 113, 49, 249, 254, 221, 168, 177, 30, 208, 116, 195, 73, 32, 110, 50, 23, 207, 220, 52, 238, 130, 50, 37, 250, 49, 153 },
                            SecondPasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            UserType = 0,
                            VerificationCode = "31",
                            VerifiedStatus = true
                        },
                        new
                        {
                            Id = 15,
                            DarkModeStatus = false,
                            Email = "aynur@dayanik",
                            Name = "Aynur Dayanik",
                            PasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            PasswordSalt = new byte[] { 93, 192, 116, 88, 137, 98, 211, 57, 165, 237, 91, 121, 203, 91, 158, 191, 186, 179, 131, 11, 226, 61, 219, 18, 163, 169, 0, 155, 127, 246, 119, 208, 73, 93, 161, 199, 237, 231, 96, 44, 244, 139, 90, 22, 167, 122, 21, 243, 154, 118, 143, 183, 232, 31, 108, 44, 122, 59, 120, 14, 188, 93, 103, 143, 215, 51, 209, 135, 106, 51, 214, 248, 12, 33, 186, 142, 154, 9, 164, 221, 230, 173, 37, 191, 195, 30, 127, 252, 71, 35, 237, 55, 102, 121, 159, 229, 243, 137, 217, 128, 170, 16, 113, 49, 249, 254, 221, 168, 177, 30, 208, 116, 195, 73, 32, 110, 50, 23, 207, 220, 52, 238, 130, 50, 37, 250, 49, 153 },
                            SecondPasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            UserType = 1,
                            VerificationCode = "31",
                            VerifiedStatus = true
                        },
                        new
                        {
                            Id = 16,
                            DarkModeStatus = false,
                            Email = "erdem@Tuna",
                            Name = "Erdem Tuna",
                            PasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            PasswordSalt = new byte[] { 93, 192, 116, 88, 137, 98, 211, 57, 165, 237, 91, 121, 203, 91, 158, 191, 186, 179, 131, 11, 226, 61, 219, 18, 163, 169, 0, 155, 127, 246, 119, 208, 73, 93, 161, 199, 237, 231, 96, 44, 244, 139, 90, 22, 167, 122, 21, 243, 154, 118, 143, 183, 232, 31, 108, 44, 122, 59, 120, 14, 188, 93, 103, 143, 215, 51, 209, 135, 106, 51, 214, 248, 12, 33, 186, 142, 154, 9, 164, 221, 230, 173, 37, 191, 195, 30, 127, 252, 71, 35, 237, 55, 102, 121, 159, 229, 243, 137, 217, 128, 170, 16, 113, 49, 249, 254, 221, 168, 177, 30, 208, 116, 195, 73, 32, 110, 50, 23, 207, 220, 52, 238, 130, 50, 37, 250, 49, 153 },
                            SecondPasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            UserType = 0,
                            VerificationCode = "31",
                            VerifiedStatus = true
                        },
                        new
                        {
                            Id = 17,
                            DarkModeStatus = false,
                            Email = "elgun@ta",
                            Name = "Elgun TA",
                            PasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            PasswordSalt = new byte[] { 93, 192, 116, 88, 137, 98, 211, 57, 165, 237, 91, 121, 203, 91, 158, 191, 186, 179, 131, 11, 226, 61, 219, 18, 163, 169, 0, 155, 127, 246, 119, 208, 73, 93, 161, 199, 237, 231, 96, 44, 244, 139, 90, 22, 167, 122, 21, 243, 154, 118, 143, 183, 232, 31, 108, 44, 122, 59, 120, 14, 188, 93, 103, 143, 215, 51, 209, 135, 106, 51, 214, 248, 12, 33, 186, 142, 154, 9, 164, 221, 230, 173, 37, 191, 195, 30, 127, 252, 71, 35, 237, 55, 102, 121, 159, 229, 243, 137, 217, 128, 170, 16, 113, 49, 249, 254, 221, 168, 177, 30, 208, 116, 195, 73, 32, 110, 50, 23, 207, 220, 52, 238, 130, 50, 37, 250, 49, 153 },
                            SecondPasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            UserType = 0,
                            VerificationCode = "31",
                            VerifiedStatus = true
                        },
                        new
                        {
                            Id = 18,
                            DarkModeStatus = false,
                            Email = "irem@reis",
                            Name = "Irem Reis",
                            PasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            PasswordSalt = new byte[] { 93, 192, 116, 88, 137, 98, 211, 57, 165, 237, 91, 121, 203, 91, 158, 191, 186, 179, 131, 11, 226, 61, 219, 18, 163, 169, 0, 155, 127, 246, 119, 208, 73, 93, 161, 199, 237, 231, 96, 44, 244, 139, 90, 22, 167, 122, 21, 243, 154, 118, 143, 183, 232, 31, 108, 44, 122, 59, 120, 14, 188, 93, 103, 143, 215, 51, 209, 135, 106, 51, 214, 248, 12, 33, 186, 142, 154, 9, 164, 221, 230, 173, 37, 191, 195, 30, 127, 252, 71, 35, 237, 55, 102, 121, 159, 229, 243, 137, 217, 128, 170, 16, 113, 49, 249, 254, 221, 168, 177, 30, 208, 116, 195, 73, 32, 110, 50, 23, 207, 220, 52, 238, 130, 50, 37, 250, 49, 153 },
                            SecondPasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            UserType = 0,
                            VerificationCode = "31",
                            VerifiedStatus = true
                        },
                        new
                        {
                            Id = 19,
                            DarkModeStatus = false,
                            Email = "fazli@can",
                            Name = "Fazli Can",
                            PasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            PasswordSalt = new byte[] { 93, 192, 116, 88, 137, 98, 211, 57, 165, 237, 91, 121, 203, 91, 158, 191, 186, 179, 131, 11, 226, 61, 219, 18, 163, 169, 0, 155, 127, 246, 119, 208, 73, 93, 161, 199, 237, 231, 96, 44, 244, 139, 90, 22, 167, 122, 21, 243, 154, 118, 143, 183, 232, 31, 108, 44, 122, 59, 120, 14, 188, 93, 103, 143, 215, 51, 209, 135, 106, 51, 214, 248, 12, 33, 186, 142, 154, 9, 164, 221, 230, 173, 37, 191, 195, 30, 127, 252, 71, 35, 237, 55, 102, 121, 159, 229, 243, 137, 217, 128, 170, 16, 113, 49, 249, 254, 221, 168, 177, 30, 208, 116, 195, 73, 32, 110, 50, 23, 207, 220, 52, 238, 130, 50, 37, 250, 49, 153 },
                            SecondPasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            UserType = 1,
                            VerificationCode = "31",
                            VerifiedStatus = true
                        },
                        new
                        {
                            Id = 20,
                            DarkModeStatus = false,
                            Email = "can@alkan",
                            Name = "Can Alkan",
                            PasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            PasswordSalt = new byte[] { 93, 192, 116, 88, 137, 98, 211, 57, 165, 237, 91, 121, 203, 91, 158, 191, 186, 179, 131, 11, 226, 61, 219, 18, 163, 169, 0, 155, 127, 246, 119, 208, 73, 93, 161, 199, 237, 231, 96, 44, 244, 139, 90, 22, 167, 122, 21, 243, 154, 118, 143, 183, 232, 31, 108, 44, 122, 59, 120, 14, 188, 93, 103, 143, 215, 51, 209, 135, 106, 51, 214, 248, 12, 33, 186, 142, 154, 9, 164, 221, 230, 173, 37, 191, 195, 30, 127, 252, 71, 35, 237, 55, 102, 121, 159, 229, 243, 137, 217, 128, 170, 16, 113, 49, 249, 254, 221, 168, 177, 30, 208, 116, 195, 73, 32, 110, 50, 23, 207, 220, 52, 238, 130, 50, 37, 250, 49, 153 },
                            SecondPasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            UserType = 1,
                            VerificationCode = "31",
                            VerifiedStatus = true
                        },
                        new
                        {
                            Id = 21,
                            DarkModeStatus = false,
                            Email = "ercument@cicek",
                            Name = "Ercument Cicek",
                            PasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            PasswordSalt = new byte[] { 93, 192, 116, 88, 137, 98, 211, 57, 165, 237, 91, 121, 203, 91, 158, 191, 186, 179, 131, 11, 226, 61, 219, 18, 163, 169, 0, 155, 127, 246, 119, 208, 73, 93, 161, 199, 237, 231, 96, 44, 244, 139, 90, 22, 167, 122, 21, 243, 154, 118, 143, 183, 232, 31, 108, 44, 122, 59, 120, 14, 188, 93, 103, 143, 215, 51, 209, 135, 106, 51, 214, 248, 12, 33, 186, 142, 154, 9, 164, 221, 230, 173, 37, 191, 195, 30, 127, 252, 71, 35, 237, 55, 102, 121, 159, 229, 243, 137, 217, 128, 170, 16, 113, 49, 249, 254, 221, 168, 177, 30, 208, 116, 195, 73, 32, 110, 50, 23, 207, 220, 52, 238, 130, 50, 37, 250, 49, 153 },
                            SecondPasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            UserType = 1,
                            VerificationCode = "31",
                            VerifiedStatus = true
                        },
                        new
                        {
                            Id = 22,
                            DarkModeStatus = false,
                            Email = "alper@karel",
                            Name = "Alper Sarikan",
                            PasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            PasswordSalt = new byte[] { 93, 192, 116, 88, 137, 98, 211, 57, 165, 237, 91, 121, 203, 91, 158, 191, 186, 179, 131, 11, 226, 61, 219, 18, 163, 169, 0, 155, 127, 246, 119, 208, 73, 93, 161, 199, 237, 231, 96, 44, 244, 139, 90, 22, 167, 122, 21, 243, 154, 118, 143, 183, 232, 31, 108, 44, 122, 59, 120, 14, 188, 93, 103, 143, 215, 51, 209, 135, 106, 51, 214, 248, 12, 33, 186, 142, 154, 9, 164, 221, 230, 173, 37, 191, 195, 30, 127, 252, 71, 35, 237, 55, 102, 121, 159, 229, 243, 137, 217, 128, 170, 16, 113, 49, 249, 254, 221, 168, 177, 30, 208, 116, 195, 73, 32, 110, 50, 23, 207, 220, 52, 238, 130, 50, 37, 250, 49, 153 },
                            SecondPasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            UserType = 1,
                            VerificationCode = "31",
                            VerifiedStatus = true
                        },
                        new
                        {
                            Id = 23,
                            DarkModeStatus = false,
                            Email = "altay@guvenir",
                            Name = "Altay Guvenir",
                            PasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            PasswordSalt = new byte[] { 93, 192, 116, 88, 137, 98, 211, 57, 165, 237, 91, 121, 203, 91, 158, 191, 186, 179, 131, 11, 226, 61, 219, 18, 163, 169, 0, 155, 127, 246, 119, 208, 73, 93, 161, 199, 237, 231, 96, 44, 244, 139, 90, 22, 167, 122, 21, 243, 154, 118, 143, 183, 232, 31, 108, 44, 122, 59, 120, 14, 188, 93, 103, 143, 215, 51, 209, 135, 106, 51, 214, 248, 12, 33, 186, 142, 154, 9, 164, 221, 230, 173, 37, 191, 195, 30, 127, 252, 71, 35, 237, 55, 102, 121, 159, 229, 243, 137, 217, 128, 170, 16, 113, 49, 249, 254, 221, 168, 177, 30, 208, 116, 195, 73, 32, 110, 50, 23, 207, 220, 52, 238, 130, 50, 37, 250, 49, 153 },
                            SecondPasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            UserType = 1,
                            VerificationCode = "31",
                            VerifiedStatus = true
                        },
                        new
                        {
                            Id = 24,
                            DarkModeStatus = false,
                            Email = "tuna@derbeder",
                            Name = "Tuna Derbeder",
                            PasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            PasswordSalt = new byte[] { 93, 192, 116, 88, 137, 98, 211, 57, 165, 237, 91, 121, 203, 91, 158, 191, 186, 179, 131, 11, 226, 61, 219, 18, 163, 169, 0, 155, 127, 246, 119, 208, 73, 93, 161, 199, 237, 231, 96, 44, 244, 139, 90, 22, 167, 122, 21, 243, 154, 118, 143, 183, 232, 31, 108, 44, 122, 59, 120, 14, 188, 93, 103, 143, 215, 51, 209, 135, 106, 51, 214, 248, 12, 33, 186, 142, 154, 9, 164, 221, 230, 173, 37, 191, 195, 30, 127, 252, 71, 35, 237, 55, 102, 121, 159, 229, 243, 137, 217, 128, 170, 16, 113, 49, 249, 254, 221, 168, 177, 30, 208, 116, 195, 73, 32, 110, 50, 23, 207, 220, 52, 238, 130, 50, 37, 250, 49, 153 },
                            SecondPasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            UserType = 0,
                            VerificationCode = "31",
                            VerifiedStatus = true
                        },
                        new
                        {
                            Id = 25,
                            DarkModeStatus = false,
                            Email = "abdul@razak",
                            Name = "Abdul Razak",
                            PasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            PasswordSalt = new byte[] { 93, 192, 116, 88, 137, 98, 211, 57, 165, 237, 91, 121, 203, 91, 158, 191, 186, 179, 131, 11, 226, 61, 219, 18, 163, 169, 0, 155, 127, 246, 119, 208, 73, 93, 161, 199, 237, 231, 96, 44, 244, 139, 90, 22, 167, 122, 21, 243, 154, 118, 143, 183, 232, 31, 108, 44, 122, 59, 120, 14, 188, 93, 103, 143, 215, 51, 209, 135, 106, 51, 214, 248, 12, 33, 186, 142, 154, 9, 164, 221, 230, 173, 37, 191, 195, 30, 127, 252, 71, 35, 237, 55, 102, 121, 159, 229, 243, 137, 217, 128, 170, 16, 113, 49, 249, 254, 221, 168, 177, 30, 208, 116, 195, 73, 32, 110, 50, 23, 207, 220, 52, 238, 130, 50, 37, 250, 49, 153 },
                            SecondPasswordHash = new byte[] { 112, 248, 159, 93, 92, 226, 15, 192, 182, 45, 55, 223, 204, 127, 20, 193, 124, 50, 127, 85, 227, 166, 191, 179, 182, 9, 160, 21, 62, 140, 191, 170, 125, 107, 71, 18, 223, 243, 78, 107, 249, 170, 62, 21, 134, 174, 50, 129, 222, 24, 50, 211, 161, 208, 237, 204, 192, 135, 171, 54, 159, 119, 153, 84 },
                            UserType = 0,
                            VerificationCode = "31",
                            VerifiedStatus = true
                        });
                });

            modelBuilder.Entity("backend.Models.Assignment", b =>
                {
                    b.HasOne("backend.Models.Section", "AffiliatedSection")
                        .WithMany()
                        .HasForeignKey("AffiliatedSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffiliatedSection");
                });

            modelBuilder.Entity("backend.Models.Comment", b =>
                {
                    b.HasOne("backend.Models.Submission", "CommentedSubmission")
                        .WithMany("Comments")
                        .HasForeignKey("CommentedSubmissionId");

                    b.HasOne("backend.Models.User", "CommentedUser")
                        .WithMany("OutgoingComments")
                        .HasForeignKey("CommentedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommentedSubmission");

                    b.Navigation("CommentedUser");
                });

            modelBuilder.Entity("backend.Models.CourseUser", b =>
                {
                    b.HasOne("backend.Models.Course", "Course")
                        .WithMany("Instructors")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("InstructedCourses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.JoinRequest", b =>
                {
                    b.HasOne("backend.Models.ProjectGroup", "RequestedGroup")
                        .WithMany("IncomingJoinRequests")
                        .HasForeignKey("RequestedGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "RequestingStudent")
                        .WithMany("OutgoingJoinRequests")
                        .HasForeignKey("RequestingStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestedGroup");

                    b.Navigation("RequestingStudent");
                });

            modelBuilder.Entity("backend.Models.MergeRequest", b =>
                {
                    b.HasOne("backend.Models.ProjectGroup", "ReceiverGroup")
                        .WithMany("IncomingMergeRequest")
                        .HasForeignKey("ReceiverGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.ProjectGroup", "SenderGroup")
                        .WithMany("OutgoingMergeRequest")
                        .HasForeignKey("SenderGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReceiverGroup");

                    b.Navigation("SenderGroup");
                });

            modelBuilder.Entity("backend.Models.PeerGrade", b =>
                {
                    b.HasOne("backend.Models.Section", "AffiliatedSection")
                        .WithMany()
                        .HasForeignKey("AffiliatedSectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.ProjectGroup", null)
                        .WithMany("PeerGrades")
                        .HasForeignKey("ProjectGroupId");

                    b.Navigation("AffiliatedSection");
                });

            modelBuilder.Entity("backend.Models.PeerGradeAssignment", b =>
                {
                    b.HasOne("backend.Models.Course", "AffiliatedCourse")
                        .WithOne("PeerGradeAssignment")
                        .HasForeignKey("backend.Models.PeerGradeAssignment", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffiliatedCourse");
                });

            modelBuilder.Entity("backend.Models.ProjectGrade", b =>
                {
                    b.HasOne("backend.Models.ProjectGroup", "GradedProjectGroup")
                        .WithMany("ProjectGrades")
                        .HasForeignKey("GradedProjectGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "GradingUser")
                        .WithMany()
                        .HasForeignKey("GradingUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradedProjectGroup");

                    b.Navigation("GradingUser");
                });

            modelBuilder.Entity("backend.Models.ProjectGroup", b =>
                {
                    b.HasOne("backend.Models.Course", "AffiliatedCourse")
                        .WithMany()
                        .HasForeignKey("AffiliatedCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Section", "AffiliatedSection")
                        .WithMany("ProjectGroups")
                        .HasForeignKey("AffiliatedSectionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AffiliatedCourse");

                    b.Navigation("AffiliatedSection");
                });

            modelBuilder.Entity("backend.Models.ProjectGroupUser", b =>
                {
                    b.HasOne("backend.Models.ProjectGroup", "ProjectGroup")
                        .WithMany("GroupMembers")
                        .HasForeignKey("ProjectGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany("ProjectGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Section", b =>
                {
                    b.HasOne("backend.Models.Course", "AffiliatedCourse")
                        .WithMany("Sections")
                        .HasForeignKey("AffiliatedCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffiliatedCourse");
                });

            modelBuilder.Entity("backend.Models.Submission", b =>
                {
                    b.HasOne("backend.Models.Assignment", "AffiliatedAssignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AffiliatedAssignmentId");

                    b.HasOne("backend.Models.ProjectGroup", "AffiliatedGroup")
                        .WithMany("Submissions")
                        .HasForeignKey("AffiliatedGroupId");

                    b.Navigation("AffiliatedAssignment");

                    b.Navigation("AffiliatedGroup");
                });

            modelBuilder.Entity("backend.Models.Assignment", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("backend.Models.Course", b =>
                {
                    b.Navigation("Instructors");

                    b.Navigation("PeerGradeAssignment");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("backend.Models.ProjectGroup", b =>
                {
                    b.Navigation("GroupMembers");

                    b.Navigation("IncomingJoinRequests");

                    b.Navigation("IncomingMergeRequest");

                    b.Navigation("OutgoingMergeRequest");

                    b.Navigation("PeerGrades");

                    b.Navigation("ProjectGrades");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("backend.Models.Section", b =>
                {
                    b.Navigation("ProjectGroups");
                });

            modelBuilder.Entity("backend.Models.Submission", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("InstructedCourses");

                    b.Navigation("OutgoingComments");

                    b.Navigation("OutgoingJoinRequests");

                    b.Navigation("ProjectGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
