// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

namespace BilHub.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CourseUser", b =>
                {
                    b.Property<int>("InstructedCoursesId")
                        .HasColumnType("int");

                    b.Property<int>("InstructorsId")
                        .HasColumnType("int");

                    b.HasKey("InstructedCoursesId", "InstructorsId");

                    b.HasIndex("InstructorsId");

                    b.ToTable("CourseUser");
                });

            modelBuilder.Entity("ProjectGroupUser", b =>
                {
                    b.Property<int>("GroupMembersId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectGroupsId")
                        .HasColumnType("int");

                    b.HasKey("GroupMembersId", "ProjectGroupsId");

                    b.HasIndex("ProjectGroupsId");

                    b.ToTable("ProjectGroupUser");
                });

            modelBuilder.Entity("backend.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AcceptedTypes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AffiliatedSectionId")
                        .HasColumnType("int");

                    b.Property<string>("AssignmentDescriptionFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CanBeGradedByStudents")
                        .HasColumnType("bit");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsItGraded")
                        .HasColumnType("bit");

                    b.Property<int>("MaxFileSizeInBytes")
                        .HasColumnType("int");

                    b.Property<bool>("VisibilityOfSubmission")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AffiliatedSectionId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("backend.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CommentedSubmissionId")
                        .HasColumnType("int");

                    b.Property<int>("CommentedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FileAttachmentAvailability")
                        .HasColumnType("bit");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Grade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxGrade")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CommentedSubmissionId");

                    b.HasIndex("CommentedUserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("backend.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseSemester")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LockDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("backend.Models.GroupSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AffiliatedCourseId")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AffiliatedCourseId");

                    b.ToTable("GroupSizes");
                });

            modelBuilder.Entity("backend.Models.JoinRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Accepted")
                        .HasColumnType("bit");

                    b.Property<int>("AcceptedNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestedGroupId")
                        .HasColumnType("int");

                    b.Property<int>("RequestingStudentId")
                        .HasColumnType("int");

                    b.Property<bool>("Resolved")
                        .HasColumnType("bit");

                    b.Property<string>("VotedStudents")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RequestedGroupId");

                    b.HasIndex("RequestingStudentId");

                    b.ToTable("JoinRequests");
                });

            modelBuilder.Entity("backend.Models.MergeRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Accepted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReceiverGroupId")
                        .HasColumnType("int");

                    b.Property<bool>("Resolved")
                        .HasColumnType("bit");

                    b.Property<int>("SenderGroupId")
                        .HasColumnType("int");

                    b.Property<string>("VotedStudents")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverGroupId");

                    b.HasIndex("SenderGroupId");

                    b.ToTable("MergeRequests");
                });

            modelBuilder.Entity("backend.Models.PeerGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AffiliatedSectionID")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Grade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxGrade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProjectGroupId")
                        .HasColumnType("int");

                    b.Property<int>("RevieweeId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AffiliatedSectionID");

                    b.HasIndex("ProjectGroupId");

                    b.ToTable("PeerGrades");
                });

            modelBuilder.Entity("backend.Models.PeerGradeAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssignmentDescriptionFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .IsUnique();

                    b.ToTable("PeerGradeAssignments");
                });

            modelBuilder.Entity("backend.Models.ProjectGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Grade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GradedProjectGroupID")
                        .HasColumnType("int");

                    b.Property<int>("GradingUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxGrade")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GradedProjectGroupID");

                    b.HasIndex("GradingUserId");

                    b.ToTable("ProjectGrades");
                });

            modelBuilder.Entity("backend.Models.ProjectGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AffiliatedCourseId")
                        .HasColumnType("int");

                    b.Property<int>("AffiliatedSectionId")
                        .HasColumnType("int");

                    b.Property<bool>("ConfirmationState")
                        .HasColumnType("bit");

                    b.Property<int>("ConfirmedUserNumber")
                        .HasColumnType("int");

                    b.Property<string>("ProjectInformation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AffiliatedCourseId");

                    b.HasIndex("AffiliatedSectionId");

                    b.ToTable("ProjectGroups");
                });

            modelBuilder.Entity("backend.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AffiliatedCourseId")
                        .HasColumnType("int");

                    b.Property<int>("SectionNo")
                        .HasColumnType("int");

                    b.Property<bool>("SectionlessState")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AffiliatedCourseId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("backend.Models.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AffiliatedAssignmentId")
                        .HasColumnType("int");

                    b.Property<int?>("AffiliatedGroupId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasSubmission")
                        .HasColumnType("bit");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AffiliatedAssignmentId");

                    b.HasIndex("AffiliatedGroupId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("DarkModeStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SecondPasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("SectionId")
                        .HasColumnType("int");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VerifiedStatus")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CourseUser", b =>
                {
                    b.HasOne("backend.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("InstructedCoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("InstructorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectGroupUser", b =>
                {
                    b.HasOne("backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("GroupMembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.ProjectGroup", null)
                        .WithMany()
                        .HasForeignKey("ProjectGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Assignment", b =>
                {
                    b.HasOne("backend.Models.Section", "AffiliatedSection")
                        .WithMany()
                        .HasForeignKey("AffiliatedSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffiliatedSection");
                });

            modelBuilder.Entity("backend.Models.Comment", b =>
                {
                    b.HasOne("backend.Models.Submission", "CommentedSubmission")
                        .WithMany("Comments")
                        .HasForeignKey("CommentedSubmissionId");

                    b.HasOne("backend.Models.User", "CommentedUser")
                        .WithMany("OutgoingComments")
                        .HasForeignKey("CommentedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommentedSubmission");

                    b.Navigation("CommentedUser");
                });

            modelBuilder.Entity("backend.Models.GroupSize", b =>
                {
                    b.HasOne("backend.Models.Course", "AffiliatedCourse")
                        .WithMany("GroupSizes")
                        .HasForeignKey("AffiliatedCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffiliatedCourse");
                });

            modelBuilder.Entity("backend.Models.JoinRequest", b =>
                {
                    b.HasOne("backend.Models.ProjectGroup", "RequestedGroup")
                        .WithMany("IncomingJoinRequests")
                        .HasForeignKey("RequestedGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "RequestingStudent")
                        .WithMany("OutgoingJoinRequests")
                        .HasForeignKey("RequestingStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestedGroup");

                    b.Navigation("RequestingStudent");
                });

            modelBuilder.Entity("backend.Models.MergeRequest", b =>
                {
                    b.HasOne("backend.Models.ProjectGroup", "ReceiverGroup")
                        .WithMany("IncomingMergeRequest")
                        .HasForeignKey("ReceiverGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.ProjectGroup", "SenderGroup")
                        .WithMany("OutgoingMergeRequest")
                        .HasForeignKey("SenderGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReceiverGroup");

                    b.Navigation("SenderGroup");
                });

            modelBuilder.Entity("backend.Models.PeerGrade", b =>
                {
                    b.HasOne("backend.Models.Section", "AffiliatedSection")
                        .WithMany()
                        .HasForeignKey("AffiliatedSectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.ProjectGroup", null)
                        .WithMany("PeerGrades")
                        .HasForeignKey("ProjectGroupId");

                    b.Navigation("AffiliatedSection");
                });

            modelBuilder.Entity("backend.Models.PeerGradeAssignment", b =>
                {
                    b.HasOne("backend.Models.Course", "AffiliatedCourse")
                        .WithOne("PeerGradeAssignment")
                        .HasForeignKey("backend.Models.PeerGradeAssignment", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffiliatedCourse");
                });

            modelBuilder.Entity("backend.Models.ProjectGrade", b =>
                {
                    b.HasOne("backend.Models.ProjectGroup", "GradedProjectGroup")
                        .WithMany("ProjectGrades")
                        .HasForeignKey("GradedProjectGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "GradingUser")
                        .WithMany()
                        .HasForeignKey("GradingUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradedProjectGroup");

                    b.Navigation("GradingUser");
                });

            modelBuilder.Entity("backend.Models.ProjectGroup", b =>
                {
                    b.HasOne("backend.Models.Course", "AffiliatedCourse")
                        .WithMany()
                        .HasForeignKey("AffiliatedCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Section", "AffiliatedSection")
                        .WithMany("ProjectGroups")
                        .HasForeignKey("AffiliatedSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffiliatedCourse");

                    b.Navigation("AffiliatedSection");
                });

            modelBuilder.Entity("backend.Models.Section", b =>
                {
                    b.HasOne("backend.Models.Course", "AffiliatedCourse")
                        .WithMany("Sections")
                        .HasForeignKey("AffiliatedCourseId");

                    b.Navigation("AffiliatedCourse");
                });

            modelBuilder.Entity("backend.Models.Submission", b =>
                {
                    b.HasOne("backend.Models.Assignment", "AffiliatedAssignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AffiliatedAssignmentId");

                    b.HasOne("backend.Models.ProjectGroup", "AffiliatedGroup")
                        .WithMany("Submissions")
                        .HasForeignKey("AffiliatedGroupId");

                    b.Navigation("AffiliatedAssignment");

                    b.Navigation("AffiliatedGroup");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.HasOne("backend.Models.Section", null)
                        .WithMany("Students")
                        .HasForeignKey("SectionId");
                });

            modelBuilder.Entity("backend.Models.Assignment", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("backend.Models.Course", b =>
                {
                    b.Navigation("GroupSizes");

                    b.Navigation("PeerGradeAssignment");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("backend.Models.ProjectGroup", b =>
                {
                    b.Navigation("IncomingJoinRequests");

                    b.Navigation("IncomingMergeRequest");

                    b.Navigation("OutgoingMergeRequest");

                    b.Navigation("PeerGrades");

                    b.Navigation("ProjectGrades");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("backend.Models.Section", b =>
                {
                    b.Navigation("ProjectGroups");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("backend.Models.Submission", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("OutgoingComments");

                    b.Navigation("OutgoingJoinRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
